### ISSUE TITLE
Sanitize problem

### ISSUE THREAD

**Issue by PhanterJR** [web2py/yatl#13]
The module sanitize was import, but it is in conflict with argument of the function __init__ in XML Object:
```python
from sanitizer import sanitize
class XML(...):
    def __init__(self, text, sanitizer=False, ....):
        if sanitize:
             text = sanitize(text, ...) # sanitize is FALSE, it is not module
```
my suggestion:
    change the arg **sanitize** to **purify** or import sanitize as **purify**
The second option don't changes the key word of the XML object (legacy code)
sorry my bad english

**Comment by PhanterJR** [comment]
I try to do a PR, but i don't know to do without send crazy_helpers.py (It is a file that I created). :(

**Comment by mdipierro** [comment]
fixed by changing the scoping, not the name. Thanks for bringing this. would be great if you could add a test to check the code.

**Comment by PhanterJR** [comment]
I will try create a test
