### ISSUE TITLE
str, unicode = bytes, str ??????????

### ISSUE THREAD

**Issue by paolopas** [web2py/yatl#24]
What is this shit line in helpers.py? Python 2/3 compatibility code or an attempt to drive developers crazy?

This is an example of the kind of errors it produces:

```
>>> from yatl import A
>>> a = A('hello', _id='1-1')
>>> a.find('a', _id='1-1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pax/.local/lib/python3.8/site-packages/yatl/helpers.py", line 293, in find
    if not value.search(str(self[key])):
AttributeError: 'str' object has no attribute 'search'
```

other example of nonsense compatibility lines are found in sanitizer.py and template.py:
`basestring = basestring`
but at least those lines do not destroy code readability

**Comment by mdipierro** [comment]
Yes just a poor attempt at py2/3 compatibility. As far as I am concerned we could deprecate py2 completely.
