### ISSUE TITLE
CAT & DOM

### ISSUE THREAD

**Issue by paolopas** [web2py/yatl#28]
```
>>> CAT().find()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pax/Job/yatl/github/yatl/yatl/helpers.py", line 304, in find
    tag = self.name.replace("/", "")
```

@mdipierro how do you want to support CAT in server DOM?

**Comment by mdipierro** [comment]
Do not understand the question. :-(

**Comment by paolopas** [comment]
What I mean is that CAT is not well supported by yatl, even not well integrated into DOM
1. The lack of **name** and **attributes** lead to many errors, to found them simply invoke a TAGGER method using name or attributes over a CAT instance.
1. CAT ctor uses a tuple (instead of a list as TAGGER does) for **children**, this break find(replace=...), \_\_delitem\_\_, append, insert
2. CAT ctor forget to set the **parent** into childrens, this will lead to troubles when traversing DOM.

**Comment by paolopas** [comment]
see PR #29 
I think that we can accept the errors that arise from the residual attempts to access CAT.**attributes**, since we do NOT want attributes on an opaque virtual element like CAT.
The **name** simplify discrimination of CAT instances from TAGGER ones avoiding the need for isinstance usage.
