### ISSUE TITLE
Make yatl lighting fast

### ISSUE THREAD

**Issue by cccaballero** [web2py/yatl#3]
According to [this](https://github.com/cccaballero/yatl-benchmark) yatl can be two times faster than jinja2 when there is no IO. So, applying some kind of IO optimization, yatl will not only be more powerful, it can also be faster than jinja2.

**Comment by mdipierro** [comment]
👍

**Comment by mdipierro** [comment]
I updated the README with an example of how to cache with yatl. In py4web this is the default behavior.
