### ISSUE TITLE
I tag(<i></i>)

### ISSUE THREAD

**Issue by PhanterJR** [web2py/yatl#6]
I tried to use the "i" tag

**traceback**
_from yatl import (
ImportError: cannot import name 'I'_

**Comment by mdipierro** [comment]
from yatl.helpers import I

**Comment by PhanterJR** [comment]
I've tried importing, however these tags are not available
I, LINK and META

my code
`from yatl import (
    DIV,
    A,
    CAT as CONCATENATE,
    I,
    HTML,
    HEAD,
    BODY,
    META,
    LINK,
    TITLE,
    NAV,
    UL,
    LI,
    MAIN,
    FOOTER,
)`

**Comment by mdipierro** [comment]
Oops. Thanks

**Comment by PhanterJR** [comment]
Issue resolved
