### ISSUE TITLE
CAT problem

### ISSUE THREAD

**Issue by PhanterJR** [web2py/yatl#8]
Is the CAT object to concatenate?
In web2py just add the TAG objects as arguments, here I have the following error:

`TypeError: __init __ () takes 2 positional arguments but 5 were given`

After taking a look at the source code I put the arguments in a list, but I get the error:

`NameError: name 'attributes' is not defined`

The source code looks like this:

`class CAT (TAGGER):`
`     def __init __ (self, children):`
`         self.children = children`
`         self.attributes = attributes`

my sugestion:

`class CAT (TAGGER):`
`     def __init __ (self, * children):`
`         self.children = children`
`         # self.attributes = attributes`

**Comment by mdipierro** [comment]
yes. can you make a PR?

**Comment by PhanterJR** [comment]
Yes

**Comment by PhanterJR** [comment]
solved
